spring.application.name=giftoos
server.port=8080
razorpay.key.id=rzp_test_Se43cDjyDtu7U6
razorpay.key.secret=msfEh3xlw48p7Cv7RsRi4ZAm
spring.datasource.url=jdbc:mysql://localhost:3306/giftos_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

